#!/bin/sh
#
# chkconfig: - 39 35
# description: Starts and stops the dualcontrl
# debianized start-stop script

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/dualctrl/sbin/DualCtrl
OPTIONS=""
PIDFILE=/var/run/dualctrl.pid

dualctrl_start()
{
	echo  "Starting DualContrl " "..."
	start-stop-daemon --start --exec $DAEMON --pidfile $PIDFILE -- $OPTIONS
	if [ $? -eq 0 ] ; then
		echo "Done."
	else
		echo "Failed."
	fi
}

dualctrl_stop()
{
	echo  "Stopping DualContrl" "..."
	start-stop-daemon --stop --exec $DAEMON --pidfile $PIDFILE
	rm -f $PIDFILE
	if [ $? -eq 0 ] ; then
		echo "Done."
	else
		echo "Failed."
	fi
}

dualctrl_status()
{
	PID=`pidof DualCtrl`
	
	if [ $PID ]; then
		echo "DualContrl (pid $PID) is running..."
	else
		echo "DualContrl is stopped."
		exit 1
	fi
}

case "$1" in
  start)
        dualctrl_start
        ;;
  stop)
        dualctrl_stop
        ;;
  restart)
        dualctrl_stop
	sleep 1
	dualctrl_start
        ;;
  status)
	dualctrl_status
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
